FROM tensorflow/tensorflow:2.20.0-gpu-jupyter

COPY requirements.txt /tmp/project-requirements.txt
RUN /usr/bin/python -m pip install --no-cache-dir --timeout 120 --retries 5 \
    -r /tmp/project-requirements.txt
