"""Transfer-guided suggestions for the separate DiT missing-space study."""

from __future__ import annotations

from common.dit_hpo_backbones import FOLLOWUP_BRANCHES, MISSING_CAPACITY_CHOICES
from common.dit_hpo_transfer import validate_transfer_manifest


def followup_initial_trials(manifest: dict, branches: list[str]) -> list[dict[str, object]]:
    """Pair source conditioning hints with every requested new backbone family.

    Args:
        manifest: Authenticated frozen source results; no scores enter new trials.
        branches: Unique opt-in backbone names selected for the new study.

    Returns:
        Partial parameter suggestions in source-rank then backbone order. The
        missing plain family receives one suggestion per excluded capacity axis.

    Raises:
        ValueError: The source manifest or backbone selection is incompatible.
    """

    frozen = validate_transfer_manifest(manifest)
    # A branch schedule must be unambiguous and part of the supported new space.
    if not branches or len(branches) != len(set(branches)) or not set(branches).issubset(FOLLOWUP_BRANCHES):
        raise ValueError("Follow-up branches must be distinct supported backbone names.")
    schedule = []
    for branch in branches:
        # Each old capacity exclusion receives an explicit starting suggestion.
        if branch == "plain_missing":
            schedule.extend({
                "dit_followup_branch": branch, "followup_missing_axis": axis
            } for axis in MISSING_CAPACITY_CHOICES)
        # New routed or mixed topologies already lie outside the first notebook.
        else:
            schedule.append({"dit_followup_branch": branch})
    return [
        {**parameters, **topology}
        for parameters in frozen["initial_trials"] for topology in schedule
    ]


def validate_followup_protocol(manifest: dict, hpo: dict) -> dict:
    """Verify that imported suggestions retain the source evaluation protocol.

    Args:
        manifest: Frozen provenance generated by freeze_transfer.
        hpo: Target public HPO arguments before storage creation. Empty optional
            mappings and omitted controls retain ordinary full-data training.
            Fixed model/wrapper changes, custom fitting, sample caps and teacher
            or ensemble protocols require a separately designed transfer. The
            standard DiT template keeps MSE evaluation while training loss may vary.

    Returns:
        A detached validated manifest suitable for sealing with the runner.

    Raises:
        ValueError: The target changes dataset, training or evaluation semantics.
    """

    frozen = validate_transfer_manifest(manifest)
    protocol = frozen["protocol"]
    keys = [
        "task", "model_name", "epochs", "fit_method", "dtype_policy", 
        "validation_source", "validation_ratio", "objective_metrics", "objective_directions"
    ]
    for key in keys:
        # Cross-study hints remain interpretable only under the declared protocol.
        if hpo.get(key) != protocol[key]:
            raise ValueError("Follow-up target protocol differs for " + key + ".")
    # Dataset aliases may differ only in letter case.
    if str(hpo.get("dataset_name", "")).lower() != protocol["dataset_name"]:
        raise ValueError("Follow-up target dataset differs from the source.")
    for key in ("max_train_samples", "max_val_samples", "teacher_network", "feature_archive_path", "search_profile"):
        # Development subsets and alternate learning protocols cannot replace the source experiment.
        if hpo.get(key) is not None:
            raise ValueError("Follow-up target protocol differs for " + key + ".")
    for key in ("fit_kwargs", "model_overrides", "wrapper_overrides", "ensemble_accuracy_kwargs"):
        # Empty defaults retain full ordinary fitting, EMA noise targets and fixed MSE evaluation.
        if hpo.get(key):
            raise ValueError("Follow-up target protocol differs for " + key + ".")
    for key in ("use_ensemble_accuracy", "use_distillation"):
        # Source ranking excludes ensemble and teacher objectives even when scores share a label.
        if hpo.get(key, False):
            raise ValueError("Follow-up target protocol differs for " + key + ".")
    return frozen
