"""Bind serializable specialist inputs to the existing model-loading APIs.

Descriptor normalization reads configuration and artifact bytes without importing
TensorFlow. The worker verifies those same identities before constructing teachers.
"""

from __future__ import annotations

from collections.abc import Mapping
import hashlib
from pathlib import Path

from common.config import load_config, normalize_training_task


def _file_identity(path: object, expected: object = None) -> tuple[str, str]:
    """Resolve one model artifact and reject changes to an already sealed digest."""

    selected = Path(path).expanduser().resolve()
    # Descriptor identities cover one complete artifact, not an inferred directory.
    if not selected.is_file():
        raise FileNotFoundError(f"Specialist teacher artifact is not a file: {selected}")
    digest = hashlib.sha256()
    with selected.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    actual = digest.hexdigest()
    # A resumed study must consume the coordinator's exact artifact bytes.
    if expected is not None and expected != actual:
        raise ValueError(f"Specialist teacher artifact identity changed: {selected}")
    return str(selected), actual


def normalize_specialist_teacher_descriptors(
    descriptors: Mapping[str, object] | None
) -> dict[str, dict[str, object]]:
    """Seal classifier .keras and native noise Config inputs without loading models.

    ``classifier`` uses ``format='keras'`` and a compiled ``path``. ``noise``
    uses ``format='config'`` and a native generation Config YAML ``path``. A
    native Config's optional model.weights_path is resolved relative to its YAML;
    an explicit descriptor weights_path can supply that artifact instead. Only
    single-file weight artifacts are accepted. Existing sha256/weights_sha256
    entries must match and are retained as immutable study identities.

    Teachers are initialization artifacts, not an implicit original-label remapping.
    Use a fresh target Dense head above a pretrained image backbone. Native UNet
    ``num_classes=None`` enables incremental vocabulary growth; a fixed full-width
    native head retains dense schedule-ID conditions. Previously trained target
    heads must already agree with that vocabulary; no output weights are relabeled.
    """

    # Omitting specialists retains the existing previous-snapshot-only API.
    if descriptors is None:
        return {}
    # The role mapping must survive ordinary YAML and subprocess transport.
    if not isinstance(descriptors, Mapping):
        raise TypeError("specialist_teacher_descriptors must be a mapping.")
    # The previous role is generated by the continual learner, not an artifact slot.
    if set(descriptors) - {"classifier", "noise"}:
        raise ValueError("Specialist teacher roles must be classifier or noise.")
    normalized = {}
    for role, descriptor in descriptors.items():
        # Each independent role owns a complete serializable artifact declaration.
        if not isinstance(descriptor, Mapping):
            raise TypeError(f"The {role} specialist descriptor must be a mapping.")
        allowed = {"format", "path", "sha256"}
        # Native Configs may pair their architecture with a separate weights file.
        if role == "noise":
            allowed.update({"weights_path", "weights_sha256"})
        # Reject ignored metadata that might otherwise appear to affect a teacher.
        if set(descriptor) - allowed:
            raise ValueError(f"Unknown {role} specialist descriptor fields: {sorted(set(descriptor) - allowed)}")
        expected_format = "keras" if role == "classifier" else "config"
        # Ordinary image teachers and native noise teachers use their existing loaders.
        if descriptor.get("format") != expected_format:
            raise ValueError(f"The {role} specialist requires format={expected_format!r}.")
        path, digest = _file_identity(descriptor["path"], descriptor.get("sha256"))
        # The Keras archive carries the classifier graph and its compilation together.
        if role == "classifier" and Path(path).suffix != ".keras":
            raise ValueError("Classifier specialists require a compiled .keras model artifact.")
        item = {"format": expected_format, "path": path, "sha256": digest}
        # Bind a native UNet recipe and every optional weight dependency now.
        if role == "noise":
            config = load_config(path)
            # Noise specialists must be ordinary native denoisers, not task runners.
            if normalize_training_task(config.training.task) != "generation" \
            or config.model.name != "unet" \
            or config.model.wrapper_name not in (None, "diffusion_model"):
                raise ValueError("A noise specialist requires a generation/unet Config with diffusion_model wrapper.")
            # Recursive specialists would escape the finite artifact declaration.
            if config.continually_learn.specialist_teacher_descriptors:
                raise ValueError("A specialist Config cannot recursively load specialist teachers.")
            weights = descriptor.get("weights_path", config.model.weights_path)
            # A supplied weight file joins the immutable teacher identity.
            if weights is not None:
                weights = Path(weights).expanduser()
                # Relative weights belong to the source Config's directory.
                if not weights.is_absolute():
                    weights = Path(path).parent / weights
                weights_path, weights_digest = _file_identity(weights, descriptor.get("weights_sha256"))
            # An architecture-only teacher is initialized through the native factory.
            else:
                # A digest cannot authenticate an absent artifact.
                if descriptor.get("weights_sha256") is not None:
                    raise ValueError("weights_sha256 requires a weights_path.")
                weights_path = weights_digest = None
            item.update(weights_path=weights_path, weights_sha256=weights_digest)
        normalized[role] = item
    return normalized


def load_specialist_teacher_descriptors(
    descriptors: Mapping[str, object] | None, 
    seed: int | None = None
) -> dict[str, object]:
    """Verify sealed files and load independent specialists through existing APIs.

    Keras restores the classifier's compile settings and optimizer. Native UNet
    Config loading preserves its own diffusion schedule, preprocessing, optimizer
    and optional initial weights; the student wrapper checks compatibility before
    distillation. An optional study seed gives each role an independent construction
    stream, so enabling another teacher does not change its initial random weights.
    This function does not train either teacher.
    """

    normalized = normalize_specialist_teacher_descriptors(descriptors)
    # Previous-only and no-KD trials allocate no specialist models.
    if not normalized:
        return {}

    import tensorflow as tf

    from common.model import get_model
    from common.runtime import configure_runtime, derive_seed


    teachers = {}
    for role, descriptor in normalized.items():
        # Each role has a reproducible draw independent of other attached roles.
        if seed is not None:
            configure_runtime(
                dtype_policy=tf.keras.mixed_precision.global_policy().name, 
                seed=derive_seed(seed, "specialist_teacher", role)
            )
        # Keras restores the ordinary image classifier's independent optimizer.
        if role == "classifier":
            teacher = tf.keras.models.load_model(descriptor["path"], compile=True, safe_mode=True)
            # Existing image-teacher training requires the caller's compile recipe.
            if not teacher.compiled or getattr(teacher, "optimizer", None) is None:
                raise ValueError("The classifier specialist must be saved with its own compile settings and optimizer.")
        # Native Config loading preserves the denoiser's own diffusion semantics.
        else:
            config = load_config(descriptor["path"])
            config.model.weights_path = descriptor["weights_path"]
            config.model.show_network_summary = False
            teacher = get_model(config)
        teachers[role] = teacher
    return teachers
